definitions:
  dto.Video:
    properties:
      category:
        type: string
      date:
        type: string
      duration:
        type: integer
      id:
        type: string
      name:
        type: string
    type: object
  dto.VideoReview:
    properties:
      evaluation:
        type: integer
      id:
        type: string
    type: object
  gin.H:
    additionalProperties: {}
    type: object
info:
  contact: {}
paths:
  /api/videos:
    get:
      consumes:
      - application/json
      description: Returns a list of 10 mock videos for the user
      produces:
      - application/json
      responses:
        "200":
          description: List of videos
          schema:
            items:
              $ref: '#/definitions/dto.Video'
            type: array
      summary: Get Videos for User
      tags:
      - Videos
    post:
      consumes:
      - application/json
      description: Returns a new list of 10 recommended videos based on user reviews
      parameters:
      - description: List of video reviews
        in: body
        name: reviews
        required: true
        schema:
          items:
            $ref: '#/definitions/dto.VideoReview'
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: List of recommended videos
          schema:
            items:
              $ref: '#/definitions/dto.Video'
            type: array
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create Review
      tags:
      - Videos
swagger: "2.0"
